# Generated by Django 3.1.7 on 2021-08-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
